#
# Automatically generated by blueprint(7).  Edit at your own risk.
#
cookbook_file('/tmp/eded041e549437d1590721f0d8dfead7859e091d.tar') do
  backup false
  group 'root'
  mode '0644'
  owner 'root'
  source 'tmp/eded041e549437d1590721f0d8dfead7859e091d.tar'
end
execute('/tmp/eded041e549437d1590721f0d8dfead7859e091d.tar') do
  command 'tar xf "/tmp/eded041e549437d1590721f0d8dfead7859e091d.tar"'
  cwd '/usr/local'
end
directory('/etc') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/anacrontab') do
  backup false
  group 'root'
  mode '0600'
  owner 'root'
  source 'etc/anacrontab'
end
directory('/etc/dhcp') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/dhcp/dhclient.conf') do
  backup false
  group 'root'
  mode '0644'
  owner 'root'
  source 'etc/dhcp/dhclient.conf'
end
directory('/etc/docker') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/docker/key.json') do
  backup false
  group 'root'
  mode '0600'
  owner 'root'
  source 'etc/docker/key.json'
end
directory('/etc') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/hosts') do
  backup false
  group 'root'
  mode '0644'
  owner 'root'
  source 'etc/hosts'
end
directory('/etc/init') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/init/print-image-id.conf') do
  backup false
  group 'root'
  mode '0644'
  owner 'root'
  source 'etc/init/print-image-id.conf'
end
directory('/etc/mail') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/mail/access.db') do
  backup false
  group 'root'
  mode '0640'
  owner 'root'
  source 'etc/mail/access.db'
end
directory('/etc/mail') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/mail/domaintable.db') do
  backup false
  group 'root'
  mode '0640'
  owner 'root'
  source 'etc/mail/domaintable.db'
end
directory('/etc/mail') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/mail/mailertable.db') do
  backup false
  group 'root'
  mode '0640'
  owner 'root'
  source 'etc/mail/mailertable.db'
end
directory('/etc/mail') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/mail/virtusertable.db') do
  backup false
  group 'root'
  mode '0640'
  owner 'root'
  source 'etc/mail/virtusertable.db'
end
directory('/etc') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/motd.rpmsave') do
  backup false
  group 'root'
  mode '0644'
  owner 'root'
  source 'etc/motd.rpmsave'
end
directory('/etc/openldap/certs') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/openldap/certs/password') do
  backup false
  group 'root'
  mode '0400'
  owner 'root'
  source 'etc/openldap/certs/password'
end
directory('/etc/pam.d') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
link('/etc/pam.d/password-auth') do
  group 'root'
  owner 'root'
  to 'password-auth-ac'
end
directory('/etc/pam.d') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/pam.d/password-auth-ac') do
  backup false
  group 'root'
  mode '0644'
  owner 'root'
  source 'etc/pam.d/password-auth-ac'
end
directory('/etc/pam.d') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
link('/etc/pam.d/postlogin') do
  group 'root'
  owner 'root'
  to 'postlogin-ac'
end
directory('/etc/pam.d') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/pam.d/system-auth-ac') do
  backup false
  group 'root'
  mode '0644'
  owner 'root'
  source 'etc/pam.d/system-auth-ac'
end
directory('/etc/pki/ca-trust/extracted/java') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/pki/ca-trust/extracted/java/cacerts') do
  backup false
  group 'root'
  mode '0444'
  owner 'root'
  source 'etc/pki/ca-trust/extracted/java/cacerts'
end
directory('/etc/pki/ca-trust/extracted/openssl') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt') do
  backup false
  group 'root'
  mode '0444'
  owner 'root'
  source 'etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt'
end
directory('/etc/pki/ca-trust/extracted/pem') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/pki/ca-trust/extracted/pem/email-ca-bundle.pem') do
  backup false
  group 'root'
  mode '0444'
  owner 'root'
  source 'etc/pki/ca-trust/extracted/pem/email-ca-bundle.pem'
end
directory('/etc/pki/ca-trust/extracted/pem') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/pki/ca-trust/extracted/pem/objsign-ca-bundle.pem') do
  backup false
  group 'root'
  mode '0444'
  owner 'root'
  source 'etc/pki/ca-trust/extracted/pem/objsign-ca-bundle.pem'
end
directory('/etc/pki/ca-trust/extracted/pem') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem') do
  backup false
  group 'root'
  mode '0444'
  owner 'root'
  source 'etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem'
end
directory('/etc/pki/java') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
link('/etc/pki/java/cacerts') do
  group 'root'
  owner 'root'
  to '/etc/pki/ca-trust/extracted/java/cacerts'
end
directory('/etc/pki/nssdb') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/pki/nssdb/cert9.db') do
  backup false
  group 'root'
  mode '0644'
  owner 'root'
  source 'etc/pki/nssdb/cert9.db'
end
directory('/etc/pki/nssdb') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/pki/nssdb/key4.db') do
  backup false
  group 'root'
  mode '0644'
  owner 'root'
  source 'etc/pki/nssdb/key4.db'
end
directory('/etc/pki/rpm-gpg') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6') do
  backup false
  group 'root'
  mode '0644'
  owner 'root'
  source 'etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6'
end
directory('/etc/pki/rpm-gpg') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/pki/rpm-gpg/RPM-GPG-KEY-amazon-beta') do
  backup false
  group 'root'
  mode '0644'
  owner 'root'
  source 'etc/pki/rpm-gpg/RPM-GPG-KEY-amazon-beta'
end
directory('/etc/pki/rpm-gpg') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/pki/rpm-gpg/RPM-GPG-KEY-amazon-ga') do
  backup false
  group 'root'
  mode '0644'
  owner 'root'
  source 'etc/pki/rpm-gpg/RPM-GPG-KEY-amazon-ga'
end
directory('/etc/pki/tls') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
link('/etc/pki/tls/cert.pem') do
  group 'root'
  owner 'root'
  to 'certs/ca-bundle.crt'
end
directory('/etc') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/securetty') do
  backup false
  group 'root'
  mode '0600'
  owner 'root'
  source 'etc/securetty'
end
directory('/etc') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/shells') do
  backup false
  group 'root'
  mode '0644'
  owner 'root'
  source 'etc/shells'
end
directory('/etc/ssh') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/ssh/sshd_config') do
  backup false
  group 'root'
  mode '0644'
  owner 'root'
  source 'etc/ssh/sshd_config'
end
directory('/etc/ssh') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/ssh/sshd_config.rpmnew') do
  backup false
  group 'root'
  mode '0600'
  owner 'root'
  source 'etc/ssh/sshd_config.rpmnew'
end
directory('/etc/sudoers.d') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/sudoers.d/cloud-init') do
  backup false
  group 'root'
  mode '0440'
  owner 'root'
  source 'etc/sudoers.d/cloud-init'
end
directory('/etc/sysconfig') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/sysconfig/authconfig') do
  backup false
  group 'root'
  mode '0644'
  owner 'root'
  source 'etc/sysconfig/authconfig'
end
directory('/etc/yum.repos.d') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/yum.repos.d/amzn-main.repo') do
  backup false
  group 'root'
  mode '0644'
  owner 'root'
  source 'etc/yum.repos.d/amzn-main.repo'
end
directory('/etc/yum.repos.d') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/yum.repos.d/amzn-nosrc.repo') do
  backup false
  group 'root'
  mode '0644'
  owner 'root'
  source 'etc/yum.repos.d/amzn-nosrc.repo'
end
directory('/etc/yum.repos.d') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/yum.repos.d/amzn-preview.repo') do
  backup false
  group 'root'
  mode '0644'
  owner 'root'
  source 'etc/yum.repos.d/amzn-preview.repo'
end
directory('/etc/yum.repos.d') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/yum.repos.d/amzn-updates.repo') do
  backup false
  group 'root'
  mode '0644'
  owner 'root'
  source 'etc/yum.repos.d/amzn-updates.repo'
end
directory('/etc/yum.repos.d') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/yum.repos.d/epel-testing.repo') do
  backup false
  group 'root'
  mode '0644'
  owner 'root'
  source 'etc/yum.repos.d/epel-testing.repo'
end
directory('/etc/yum.repos.d') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/yum.repos.d/epel.repo') do
  backup false
  group 'root'
  mode '0644'
  owner 'root'
  source 'etc/yum.repos.d/epel.repo'
end
execute('yum makecache')
package('acl') { version '2.2.49-6.11.amzn1.x86_64' }
package('acpid') { version '2.0.19-6.7.amzn1.x86_64' }
package('alsa-lib') { version '1.0.22-3.9.amzn1.x86_64' }
package('amazon-ssm-agent') { version '2.2.120.0-1.amzn1.x86_64' }
package('at') { version '3.1.10-48.15.amzn1.x86_64' }
package('attr') { version '2.4.46-12.10.amzn1.x86_64' }
package('audit') { version '2.6.5-3.28.amzn1.x86_64' }
package('audit-libs') { version '2.6.5-3.28.amzn1.x86_64' }
package('authconfig') { version '6.2.8-30.31.amzn1.x86_64' }
package('autogen-libopts') { version '5.18-5.8.amzn1.x86_64' }
package('aws-amitools-ec2') { version '1.5.13-0.2.amzn1.noarch' }
package('aws-apitools-as') { version '1.0.61.6-1.0.amzn1.noarch' }
package('aws-apitools-common') { version '1.1.0-1.9.amzn1.noarch' }
package('aws-apitools-ec2') { version '1.7.3.0-1.0.amzn1.noarch' }
package('aws-apitools-elb') { version '1.0.35.0-1.0.amzn1.noarch' }
package('aws-apitools-mon') { version '1.0.20.0-1.0.amzn1.noarch' }
package('aws-cfn-bootstrap') { version '1.4-30.21.amzn1.noarch' }
package('aws-cli') { version '1.14.9-1.48.amzn1.noarch' }
package('basesystem') { version '10.0-4.9.amzn1.noarch' }
package('bash') { version '4.2.46-28.37.amzn1.x86_64' }
package('bc') { version '1.06.95-1.10.amzn1.x86_64' }
package('bind-libs') { version '32:9.8.2-0.62.rc1.57.amzn1.x86_64' }
package('bind-utils') { version '32:9.8.2-0.62.rc1.57.amzn1.x86_64' }
package('binutils') { version '2.25.1-31.base.66.amzn1.x86_64' }
package('bzip2') { version '1.0.6-8.12.amzn1.x86_64' }
package('bzip2-libs') { version '1.0.6-8.12.amzn1.x86_64' }
package('ca-certificates') { version '2017.2.14-65.0.1.17.amzn1.noarch' }
package('checkpolicy') { version '2.1.10-1.9.amzn1.x86_64' }
package('chef') { version '14.2.0-1.el6.x86_64' }
package('chefdk') { version '3.0.36-1.el6.x86_64' }
package('chkconfig') { version '1.3.49.3-2.14.amzn1.x86_64' }
package('cloud-disk-utils') { version '0.27-1.5.amzn1.noarch' }
package('cloud-init') { version '0.7.6-2.16.amzn1.noarch' }
package('coreutils') { version '8.22-15.52.amzn1.x86_64' }
package('cpio') { version '2.10-12.12.amzn1.x86_64' }
package('cracklib') { version '2.8.16-4.14.amzn1.x86_64' }
package('cracklib-dicts') { version '2.8.16-4.14.amzn1.x86_64' }
package('cronie') { version '1.4.4-15.8.amzn1.x86_64' }
package('cronie-anacron') { version '1.4.4-15.8.amzn1.x86_64' }
package('crontabs') { version '1.10-33.9.amzn1.noarch' }
package('cryptsetup') { version '1.6.7-1.22.amzn1.x86_64' }
package('cryptsetup-libs') { version '1.6.7-1.22.amzn1.x86_64' }
package('curl') { version '7.53.1-16.84.amzn1.x86_64' }
package('cyrus-sasl') { version '2.1.23-13.16.amzn1.x86_64' }
package('cyrus-sasl-lib') { version '2.1.23-13.16.amzn1.x86_64' }
package('cyrus-sasl-plain') { version '2.1.23-13.16.amzn1.x86_64' }
package('dash') { version '0.5.5.1-4.5.amzn1.x86_64' }
package('db4') { version '4.7.25-18.11.amzn1.x86_64' }
package('db4-utils') { version '4.7.25-18.11.amzn1.x86_64' }
package('dbus') { version '1:1.6.12-14.28.amzn1.x86_64' }
package('dbus-libs') { version '1:1.6.12-14.28.amzn1.x86_64' }
package('dejavu-fonts-common') { version '2.33-6.6.amzn1.noarch' }
package('dejavu-sans-fonts') { version '2.33-6.6.amzn1.noarch' }
package('dejavu-serif-fonts') { version '2.33-6.6.amzn1.noarch' }
package('device-mapper') { version '1.02.135-1.31.amzn1.x86_64' }
package('device-mapper-event') { version '1.02.135-1.31.amzn1.x86_64' }
package('device-mapper-event-libs') { version '1.02.135-1.31.amzn1.x86_64' }
package('device-mapper-libs') { version '1.02.135-1.31.amzn1.x86_64' }
package('device-mapper-persistent-data') { version '0.6.3-1.11.amzn1.x86_64' }
package('dhclient') { version '12:4.1.1-53.P1.28.amzn1.x86_64' }
package('dhcp-common') { version '12:4.1.1-53.P1.28.amzn1.x86_64' }
package('diffutils') { version '3.3-4.15.amzn1.x86_64' }
package('dmraid') { version '1.0.0.rc16-11.8.amzn1.x86_64' }
package('dmraid-events') { version '1.0.0.rc16-11.8.amzn1.x86_64' }
package('docker') { version '18.03.1ce-2.141.amzn1.x86_64' }
package('dracut') { version '004-409.31.amzn1.noarch' }
package('dracut-modules-growroot') { version '0.20-1.5.amzn1.noarch' }
package('dump') { version '1:0.4-0.6.b42.7.amzn1.x86_64' }
package('e2fsprogs') { version '1.42.12-4.40.amzn1.x86_64' }
package('e2fsprogs-libs') { version '1.42.12-4.40.amzn1.x86_64' }
package('ec2-net-utils') { version '0.5-1.34.amzn1.noarch' }
package('ec2-utils') { version '0.5-1.34.amzn1.noarch' }
package('ed') { version '1.1-3.3.8.amzn1.x86_64' }
package('elfutils-libelf') { version '0.168-8.19.amzn1.x86_64' }
package('epel-release') { version '6-8.9.amzn1.noarch' }
package('ethtool') { version '2:3.15-2.27.amzn1.x86_64' }
package('expat') { version '2.1.0-10.21.amzn1.x86_64' }
package('file') { version '5.30-11.34.amzn1.x86_64' }
package('file-libs') { version '5.30-11.34.amzn1.x86_64' }
package('filesystem') { version '2.4.30-3.8.amzn1.x86_64' }
package('findutils') { version '1:4.4.2-6.9.amzn1.x86_64' }
package('fipscheck-lib') { version '1.3.1-3.13.amzn1.x86_64' }
package('fontconfig') { version '2.8.0-5.8.amzn1.x86_64' }
package('fontpackages-filesystem') { version '1.41-1.1.2.amzn1.noarch' }
package('freetype') { version '2.3.11-15.14.amzn1.x86_64' }
package('gawk') { version '3.1.7-10.10.amzn1.x86_64' }
package('gdbm') { version '1.8.0-36.6.amzn1.x86_64' }
package('gdisk') { version '0.8.10-1.5.amzn1.x86_64' }
package('generic-logos') { version '17.0.0-2.5.amzn1.noarch' }
package('get_reference_source') { version '1.2-0.4.amzn1.noarch' }
package('giflib') { version '4.1.6-3.1.6.amzn1.x86_64' }
package('git') { version '2.14.4-2.58.amzn1.x86_64' }
package('glib2') { version '2.36.3-5.18.amzn1.x86_64' }
package('glibc') { version '2.17-222.173.amzn1.x86_64' }
package('glibc-common') { version '2.17-222.173.amzn1.x86_64' }
package('gmp') { version '6.0.0-11.16.amzn1.x86_64' }
package('gnupg2') { version '2.0.28-2.31.amzn1.x86_64' }
package('gpgme') { version '1.4.3-5.15.amzn1.x86_64' }
package('gpm-libs') { version '1.20.6-12.8.amzn1.x86_64' }
package('grep') { version '2.20-3.18.amzn1.x86_64' }
package('groff') { version '1.22.2-8.11.amzn1.x86_64' }
package('groff-base') { version '1.22.2-8.11.amzn1.x86_64' }
package('grub') { version '1:0.97-94.30.amzn1.x86_64' }
package('grubby') { version '7.0.15-7.8.amzn1.x86_64' }
package('gzip') { version '1.5-9.19.amzn1.x86_64' }
package('hesiod') { version '3.1.0-19.6.amzn1.x86_64' }
package('hibagent') { version '1.0.0-3.amzn1.noarch' }
package('hmaccalc') { version '0.9.12-1.9.amzn1.x86_64' }
package('hwdata') { version '0.233-14.1.19.amzn1.noarch' }
package('info') { version '5.1-4.10.amzn1.x86_64' }
package('initscripts') { version '9.03.58-1.39.amzn1.x86_64' }
package('iproute') { version '4.4.0-3.23.amzn1.x86_64' }
package('iptables') { version '1.4.18-1.22.amzn1.x86_64' }
package('iputils') { version '20121221-7.13.amzn1.x86_64' }
package('irqbalance') { version '2:1.3.0-1.26.amzn1.x86_64' }
package('java-1.7.0-openjdk') { version '1:1.7.0.181-2.6.14.8.80.amzn1.x86_64' }
package('javapackages-tools') { version '0.9.1-1.5.amzn1.noarch' }
package('jpackage-utils') { version '0:1.7.5-27.17.amzn1.noarch' }
package('kbd') { version '1.15-11.4.amzn1.x86_64' }
package('kbd-misc') { version '1.15-11.4.amzn1.noarch' }
package('kernel') { version '4.14.33-51.37.amzn1.x86_64' }
package('kernel') { version '4.14.47-56.37.amzn1.x86_64' }
package('kernel-tools') { version '4.14.47-56.37.amzn1.x86_64' }
package('kmod') { version '14-10.10.amzn1.x86_64' }
package('kmod-libs') { version '14-10.10.amzn1.x86_64' }
package('kpartx') { version '0.4.9-72.8.amzn1.x86_64' }
package('krb5-libs') { version '1.15.1-8.43.amzn1.x86_64' }
package('lcms2') { version '2.6-2.5.amzn1.x86_64' }
package('less') { version '436-13.12.amzn1.x86_64' }
package('libICE') { version '1.0.6-1.4.amzn1.x86_64' }
package('libSM') { version '1.2.1-2.6.amzn1.x86_64' }
package('libX11') { version '1.6.0-2.2.12.amzn1.x86_64' }
package('libX11-common') { version '1.6.0-2.2.12.amzn1.x86_64' }
package('libXau') { version '1.0.6-4.9.amzn1.x86_64' }
package('libXcomposite') { version '0.4.3-4.6.amzn1.x86_64' }
package('libXext') { version '1.3.2-2.1.10.amzn1.x86_64' }
package('libXfont') { version '1.4.5-5.12.amzn1.x86_64' }
package('libXi') { version '1.7.2-2.2.9.amzn1.x86_64' }
package('libXrender') { version '0.9.8-2.1.9.amzn1.x86_64' }
package('libXtst') { version '1.2.2-2.1.9.amzn1.x86_64' }
package('libacl') { version '2.2.49-6.11.amzn1.x86_64' }
package('libaio') { version '0.3.109-12.8.amzn1.x86_64' }
package('libassuan') { version '2.0.3-3.3.amzn1.x86_64' }
package('libattr') { version '2.4.46-12.10.amzn1.x86_64' }
package('libcap') { version '2.16-5.5.8.amzn1.x86_64' }
package('libcap-ng') { version '0.7.5-4.15.amzn1.x86_64' }
package('libcgroup') { version '0.40.rc1-5.11.amzn1.x86_64' }
package('libcom_err') { version '1.42.12-4.40.amzn1.x86_64' }
package('libcurl') { version '7.53.1-16.84.amzn1.x86_64' }
package('libedit') { version '2.11-4.20080712cvs.1.6.amzn1.x86_64' }
package('libevent') { version '2.0.21-4.19.amzn1.x86_64' }
package('libffi') { version '3.0.13-16.5.amzn1.x86_64' }
package('libfontenc') { version '1.0.5-2.6.amzn1.x86_64' }
package('libgcc72') { version '7.2.1-2.59.amzn1.x86_64' }
package('libgcrypt') { version '1.5.3-12.19.amzn1.x86_64' }
package('libgpg-error') { version '1.11-1.12.amzn1.x86_64' }
package('libgssglue') { version '0.1-11.7.amzn1.x86_64' }
package('libicu') { version '50.1.2-11.12.amzn1.x86_64' }
package('libidn') { version '1.18-2.8.amzn1.x86_64' }
package('libidn2') { version '0.16-1.2.amzn1.x86_64' }
package('libjpeg-turbo') { version '1.2.90-5.14.amzn1.x86_64' }
package('libmount') { version '2.23.2-33.28.amzn1.x86_64' }
package('libnfsidmap') { version '0.25-11.10.amzn1.x86_64' }
package('libnghttp2') { version '1.21.1-1.4.amzn1.x86_64' }
package('libnih') { version '1.0.1-7.8.amzn1.x86_64' }
package('libnl') { version '1.1.4-2.10.amzn1.x86_64' }
package('libpipeline') { version '1.2.3-3.3.amzn1.x86_64' }
package('libpng') { version '2:1.2.49-2.14.amzn1.x86_64' }
package('libpsl') { version '0.6.2-1.2.amzn1.x86_64' }
package('libpwquality') { version '1.2.3-4.8.amzn1.x86_64' }
package('libseccomp') { version '2.3.1-2.4.amzn1.x86_64' }
package('libselinux') { version '2.1.10-3.22.amzn1.x86_64' }
package('libselinux-utils') { version '2.1.10-3.22.amzn1.x86_64' }
package('libsemanage') { version '2.1.6-3.13.amzn1.x86_64' }
package('libsepol') { version '2.1.7-3.12.amzn1.x86_64' }
package('libss') { version '1.42.12-4.40.amzn1.x86_64' }
package('libssh2') { version '1.4.2-2.13.amzn1.x86_64' }
package('libstdc++72') { version '7.2.1-2.59.amzn1.x86_64' }
package('libsysfs') { version '2.1.0-7.10.amzn1.x86_64' }
package('libtasn1') { version '2.3-6.6.amzn1.x86_64' }
package('libtirpc') { version '0.2.4-0.8.14.amzn1.x86_64' }
package('libtool-ltdl') { version '2.4.2-20.4.8.5.32.amzn1.x86_64' }
package('libudev') { version '173-4.13.amzn1.x86_64' }
package('libunistring') { version '0.9.3-6.1.amzn1.x86_64' }
package('libuser') { version '0.60-7.23.amzn1.x86_64' }
package('libutempter') { version '1.1.5-4.1.6.amzn1.x86_64' }
package('libverto') { version '0.2.5-4.9.amzn1.x86_64' }
package('libxcb') { version '1.11-2.21.amzn1.x86_64' }
package('libxml2') { version '2.9.1-6.3.49.amzn1.x86_64' }
package('libxml2-python27') { version '2.9.1-6.3.49.amzn1.x86_64' }
package('libxslt') { version '1.1.28-5.12.amzn1.x86_64' }
package('libyaml') { version '0.1.6-6.7.amzn1.x86_64' }
package('logrotate') { version '3.7.8-26.14.amzn1.x86_64' }
package('lsof') { version '4.82-5.11.amzn1.x86_64' }
package('lua') { version '5.1.4-4.1.9.amzn1.x86_64' }
package('lvm2') { version '2.02.166-1.31.amzn1.x86_64' }
package('lvm2-libs') { version '2.02.166-1.31.amzn1.x86_64' }
package('mailcap') { version '2.1.31-2.7.amzn1.noarch' }
package('make') { version '1:3.82-21.10.amzn1.x86_64' }
package('man-db') { version '2.6.3-9.3.amzn1.x86_64' }
package('man-pages') { version '4.10-2.16.amzn1.noarch' }
package('mdadm') { version '3.2.6-7.32.amzn1.x86_64' }
package('mingetty') { version '1.08-5.9.amzn1.x86_64' }
package('nano') { version '2.5.3-1.19.amzn1.x86_64' }
package('nc') { version '1.84-24.8.amzn1.x86_64' }
package('ncurses') { version '5.7-4.20090207.14.amzn1.x86_64' }
package('ncurses-base') { version '5.7-4.20090207.14.amzn1.x86_64' }
package('ncurses-libs') { version '5.7-4.20090207.14.amzn1.x86_64' }
package('net-tools') { version '1.60-110.10.amzn1.x86_64' }
package('newt') { version '0.52.11-3.11.amzn1.x86_64' }
package('newt-python27') { version '0.52.11-3.11.amzn1.x86_64' }
package('nfs-utils') { version '1:1.3.0-0.21.amzn1.x86_64' }
package('nspr') { version '4.13.1-1.0.39.amzn1.x86_64' }
package('nss') { version '3.28.4-12.80.amzn1.x86_64' }
package('nss-pem') { version '1.0.3-4.3.amzn1.x86_64' }
package('nss-softokn') { version '3.28.3-8.41.amzn1.x86_64' }
package('nss-softokn-freebl') { version '3.28.3-8.41.amzn1.x86_64' }
package('nss-sysinit') { version '3.28.4-12.80.amzn1.x86_64' }
package('nss-tools') { version '3.28.4-12.80.amzn1.x86_64' }
package('nss-util') { version '3.28.4-3.53.amzn1.x86_64' }
package('ntp') { version '4.2.8p11-2.38.amzn1.x86_64' }
package('ntpdate') { version '4.2.8p11-2.38.amzn1.x86_64' }
package('ntsysv') { version '1.3.49.3-2.14.amzn1.x86_64' }
package('numactl') { version '2.0.7-8.11.amzn1.x86_64' }
package('openldap') { version '2.4.40-12.30.amzn1.x86_64' }
package('openssh') { version '7.4p1-16.69.amzn1.x86_64' }
package('openssh-clients') { version '7.4p1-16.69.amzn1.x86_64' }
package('openssh-server') { version '7.4p1-16.69.amzn1.x86_64' }
package('openssl') { version '1:1.0.2k-12.109.amzn1.x86_64' }
package('p11-kit') { version '0.18.5-2.3.amzn1.x86_64' }
package('p11-kit-trust') { version '0.18.5-2.3.amzn1.x86_64' }
package('pam') { version '1.1.8-12.33.amzn1.x86_64' }
package('pam_ccreds') { version '10-4.9.amzn1.x86_64' }
package('pam_krb5') { version '2.3.11-9.12.amzn1.x86_64' }
package('pam_passwdqc') { version '1.0.5-6.8.amzn1.x86_64' }
package('parted') { version '2.1-21.18.amzn1.x86_64' }
package('passwd') { version '0.79-4.13.amzn1.x86_64' }
package('pciutils') { version '3.1.10-4.11.amzn1.x86_64' }
package('pciutils-libs') { version '3.1.10-4.11.amzn1.x86_64' }
package('pcre') { version '8.21-7.7.amzn1.x86_64' }
package('perl') { version '4:5.16.3-286.38.amzn1.x86_64' }
package('perl-Carp') { version '1.26-244.5.amzn1.noarch' }
package('perl-Digest') { version '1.17-245.5.amzn1.noarch' }
package('perl-Digest-HMAC') { version '1.03-5.7.amzn1.noarch' }
package('perl-Digest-MD5') { version '2.52-3.5.amzn1.x86_64' }
package('perl-Digest-SHA') { version '1:5.85-3.5.amzn1.x86_64' }
package('perl-Encode') { version '2.51-7.5.amzn1.x86_64' }
package('perl-Error') { version '1:0.17020-2.9.amzn1.noarch' }
package('perl-Exporter') { version '5.68-3.5.amzn1.noarch' }
package('perl-File-Path') { version '2.09-2.5.amzn1.noarch' }
package('perl-File-Temp') { version '0.23.01-3.5.amzn1.noarch' }
package('perl-Filter') { version '1.49-3.5.amzn1.x86_64' }
package('perl-Getopt-Long') { version '2.40-2.5.amzn1.noarch' }
package('perl-Git') { version '2.14.4-2.58.amzn1.noarch' }
package('perl-HTTP-Tiny') { version '0.033-3.6.amzn1.noarch' }
package('perl-PathTools') { version '3.40-5.5.amzn1.x86_64' }
package('perl-Pod-Escapes') { version '1:1.04-286.38.amzn1.noarch' }
package('perl-Pod-Perldoc') { version '3.20-4.7.amzn1.noarch' }
package('perl-Pod-Simple') { version '1:3.28-4.6.amzn1.noarch' }
package('perl-Pod-Usage') { version '1.63-3.5.amzn1.noarch' }
package('perl-Scalar-List-Utils') { version '1.27-248.5.amzn1.x86_64' }
package('perl-Socket') { version '2.010-3.5.amzn1.x86_64' }
package('perl-Storable') { version '2.45-3.5.amzn1.x86_64' }
package('perl-TermReadKey') { version '2.30-20.9.amzn1.x86_64' }
package('perl-Text-ParseWords') { version '3.29-4.5.amzn1.noarch' }
package('perl-Time-HiRes') { version '4:1.9725-272.5.amzn1.x86_64' }
package('perl-Time-Local') { version '1.2300-2.5.amzn1.noarch' }
package('perl-constant') { version '1.27-2.5.amzn1.noarch' }
package('perl-libs') { version '4:5.16.3-286.38.amzn1.x86_64' }
package('perl-macros') { version '4:5.16.3-286.38.amzn1.x86_64' }
package('perl-parent') { version '1:0.225-244.5.amzn1.noarch' }
package('perl-podlators') { version '2.5.1-3.8.amzn1.noarch' }
package('perl-threads') { version '1.87-4.5.amzn1.x86_64' }
package('perl-threads-shared') { version '1.43-6.5.amzn1.x86_64' }
package('pinentry') { version '0.7.6-6.11.amzn1.x86_64' }
package('pkgconfig') { version '1:0.27.1-2.7.amzn1.x86_64' }
package('pm-utils') { version '1.4.1-31.2.amzn1.x86_64' }
package('policycoreutils') { version '2.1.12-5.25.amzn1.x86_64' }
package('popt') { version '1.13-7.7.amzn1.x86_64' }
package('procmail') { version '3.22-25.1.6.amzn1.x86_64' }
package('procps') { version '3.2.8-30.14.amzn1.x86_64' }
package('psacct') { version '6.3.2-63.8.amzn1.x86_64' }
package('psmisc') { version '22.20-8.12.amzn1.x86_64' }
package('pth') { version '2.0.7-9.3.7.amzn1.x86_64' }
package('python27') { version '2.7.14-1.123.amzn1.x86_64' }
package('python27-PyYAML') { version '3.10-3.10.amzn1.x86_64' }
package('python27-babel') { version '0.9.4-5.1.8.amzn1.noarch' }
package('python27-backports') { version '1.0-3.14.amzn1.x86_64' }
package('python27-backports-ssl_match_hostname') { version '3.4.0.2-1.12.amzn1.noarch' }
package('python27-boto') { version '2.48.0-1.2.amzn1.noarch' }
package('python27-botocore') { version '1.8.13-1.66.amzn1.noarch' }
package('python27-chardet') { version '2.0.1-7.7.amzn1.noarch' }
package('python27-colorama') { version '0.2.5-1.7.amzn1.noarch' }
package('python27-configobj') { version '4.7.2-7.15.amzn1.noarch' }
package('python27-crypto') { version '2.6.1-1.15.amzn1.x86_64' }
package('python27-daemon') { version '1.5.2-1.5.amzn1.noarch' }
package('python27-dateutil') { version '2.1-1.3.amzn1.noarch' }
package('python27-devel') { version '2.7.14-1.123.amzn1.x86_64' }
package('python27-docutils') { version '0.11-1.15.amzn1.noarch' }
package('python27-ecdsa') { version '0.11-3.3.amzn1.noarch' }
package('python27-futures') { version '3.0.3-1.3.amzn1.noarch' }
package('python27-imaging') { version '1.1.6-19.9.amzn1.x86_64' }
package('python27-iniparse') { version '0.3.1-2.1.9.amzn1.noarch' }
package('python27-jinja2') { version '2.7.2-2.15.amzn1.noarch' }
package('python27-jmespath') { version '0.9.2-1.12.amzn1.noarch' }
package('python27-jsonpatch') { version '1.2-2.5.amzn1.noarch' }
package('python27-jsonpointer') { version '1.0-3.4.amzn1.noarch' }
package('python27-kitchen') { version '1.1.1-5.6.amzn1.noarch' }
package('python27-libs') { version '2.7.14-1.123.amzn1.x86_64' }
package('python27-lockfile') { version '0.8-3.5.amzn1.noarch' }
package('python27-markupsafe') { version '0.11-4.6.amzn1.x86_64' }
package('python27-paramiko') { version '1.15.1-2.6.amzn1.noarch' }
package('python27-pip') { version '9.0.3-1.26.amzn1.noarch' }
package('python27-ply') { version '3.4-3.12.amzn1.noarch' }
package('python27-pyasn1') { version '0.1.7-2.9.amzn1.noarch' }
package('python27-pycurl') { version '7.19.0-17.12.amzn1.x86_64' }
package('python27-pygpgme') { version '0.3-9.12.amzn1.x86_64' }
package('python27-pyliblzma') { version '0.5.3-11.6.amzn1.x86_64' }
package('python27-pystache') { version '0.5.3-2.8.amzn1.noarch' }
package('python27-pyxattr') { version '0.5.0-1.6.amzn1.x86_64' }
package('python27-requests') { version '1.2.3-5.10.amzn1.noarch' }
package('python27-rsa') { version '3.4.1-1.8.amzn1.noarch' }
package('python27-setuptools') { version '36.2.7-1.33.amzn1.noarch' }
package('python27-simplejson') { version '3.6.5-1.12.amzn1.x86_64' }
package('python27-six') { version '1.8.0-1.23.amzn1.noarch' }
package('python27-urlgrabber') { version '3.10-8.16.amzn1.noarch' }
package('python27-urllib3') { version '1.8.2-1.5.amzn1.noarch' }
package('python27-virtualenv') { version '15.1.0-1.14.amzn1.noarch' }
package('quota') { version '1:4.00-7.18.amzn1.x86_64' }
package('quota-nls') { version '1:4.00-7.18.amzn1.noarch' }
package('readline') { version '6.2-9.14.amzn1.x86_64' }
package('rmt') { version '1:0.4-0.6.b42.7.amzn1.x86_64' }
package('rng-tools') { version '5-11.13.amzn1.x86_64' }
package('rootfiles') { version '8.1-6.1.8.amzn1.noarch' }
package('rpcbind') { version '0.2.0-13.10.amzn1.x86_64' }
package('rpm') { version '4.11.3-21.75.amzn1.x86_64' }
package('rpm-build-libs') { version '4.11.3-21.75.amzn1.x86_64' }
package('rpm-libs') { version '4.11.3-21.75.amzn1.x86_64' }
package('rpm-python27') { version '4.11.3-21.75.amzn1.x86_64' }
package('rsync') { version '3.0.6-12.13.amzn1.x86_64' }
package('rsyslog') { version '5.8.10-9.26.amzn1.x86_64' }
package('ruby') { version '1:2.0-0.3.amzn1.noarch' }
package('ruby20') { version '2.0.0.648-1.31.amzn1.x86_64' }
package('ruby20-irb') { version '2.0.0.648-1.31.amzn1.noarch' }
package('ruby20-libs') { version '2.0.0.648-1.31.amzn1.x86_64' }
package('rubygem20-bigdecimal') { version '1.2.0-1.31.amzn1.x86_64' }
package('rubygem20-json') { version '1.8.3-1.51.amzn1.x86_64' }
package('rubygem20-psych') { version '2.0.0-1.31.amzn1.x86_64' }
package('rubygem20-rdoc') { version '4.2.2-1.43.amzn1.noarch' }
package('rubygems20') { version '2.0.14.1-1.31.amzn1.noarch' }
package('screen') { version '4.0.3-19.6.amzn1.x86_64' }
package('sed') { version '4.2.1-10.10.amzn1.x86_64' }
package('sendmail') { version '8.14.4-9.14.amzn1.x86_64' }
package('setserial') { version '2.17-25.7.amzn1.x86_64' }
package('setup') { version '2.8.14-20.12.amzn1.noarch' }
package('shadow-utils') { version '2:4.1.4.2-13.10.amzn1.x86_64' }
package('shared-mime-info') { version '1.1-9.8.amzn1.x86_64' }
package('slang') { version '2.2.1-1.8.amzn1.x86_64' }
package('sqlite') { version '3.7.17-8.14.amzn1.x86_64' }
package('sudo') { version '1.8.6p3-29.27.amzn1.x86_64' }
package('sysctl-defaults') { version '1.0-1.1.amzn1.noarch' }
package('sysfsutils') { version '2.1.0-7.10.amzn1.x86_64' }
package('system-release') { version '2018.03-0.0.noarch' }
package('sysvinit') { version '2.87-6.dsf.15.amzn1.x86_64' }
package('tar') { version '2:1.26-31.22.amzn1.x86_64' }
package('tcp_wrappers') { version '7.6-77.12.amzn1.x86_64' }
package('tcp_wrappers-libs') { version '7.6-77.12.amzn1.x86_64' }
package('time') { version '1.7-38.9.amzn1.x86_64' }
package('tmpwatch') { version '2.9.16-4.10.amzn1.x86_64' }
package('traceroute') { version '3:2.0.14-2.7.amzn1.x86_64' }
package('ttmkfdir') { version '3.0.9-32.1.5.amzn1.x86_64' }
package('tzdata') { version '2018c-1.70.amzn1.noarch' }
package('tzdata-java') { version '2018c-1.70.amzn1.noarch' }
package('udev') { version '173-4.13.amzn1.x86_64' }
package('unzip') { version '6.0-4.10.amzn1.x86_64' }
package('update-motd') { version '1.0.1-3.0.amzn1.noarch' }
package('upstart') { version '0.6.5-13.3.13.amzn1.x86_64' }
package('ustr') { version '1.0.4-9.1.6.amzn1.x86_64' }
package('util-linux') { version '2.23.2-33.28.amzn1.x86_64' }
package('vim-common') { version '2:8.0.0503-1.45.amzn1.x86_64' }
package('vim-enhanced') { version '2:8.0.0503-1.45.amzn1.x86_64' }
package('vim-filesystem') { version '2:8.0.0503-1.45.amzn1.x86_64' }
package('vim-minimal') { version '2:8.0.0503-1.45.amzn1.x86_64' }
package('wget') { version '1.18-4.29.amzn1.x86_64' }
package('which') { version '2.19-6.10.amzn1.x86_64' }
package('words') { version '3.0-17.8.amzn1.noarch' }
package('xfsprogs') { version '4.5.0-9.21.amzn1.x86_64' }
package('xorg-x11-font-utils') { version '1:7.2-11.5.amzn1.x86_64' }
package('xorg-x11-fonts-Type1') { version '7.2-9.1.5.amzn1.noarch' }
package('xz') { version '5.1.2-12alpha.12.amzn1.x86_64' }
package('xz-libs') { version '5.1.2-12alpha.12.amzn1.x86_64' }
package('yum-metadata-parser') { version '1.1.4-10.20.amzn1.x86_64' }
package('yum-plugin-priorities') { version '1.1.31-40.29.amzn1.noarch' }
package('yum-plugin-upgrade-helper') { version '1.1.31-40.29.amzn1.noarch' }
package('yum-utils') { version '1.1.31-40.29.amzn1.noarch' }
package('zip') { version '3.0-1.10.amzn1.x86_64' }
package('zlib') { version '1.2.8-7.18.amzn1.x86_64' }
service('acpid') do
  action [:enable, :start]
  subscribes :restart, resources('package[acpid]')
end
service('atd') do
  action [:enable, :start]
  subscribes :restart, resources('package[at]')
end
service('auditd') do
  action [:enable, :start]
  subscribes :restart, resources('package[audit]')
end
service('cloud-config') do
  action [:enable, :start]
  subscribes :restart, resources('cookbook_file[/etc/sudoers.d/cloud-init]', 'package[cloud-init]')
end
service('cloud-final') do
  action [:enable, :start]
  subscribes :restart, resources('cookbook_file[/etc/sudoers.d/cloud-init]', 'package[cloud-init]')
end
service('cloud-init') do
  action [:enable, :start]
  subscribes :restart, resources('cookbook_file[/etc/sudoers.d/cloud-init]', 'package[cloud-init]')
end
service('cloud-init-local') do
  action [:enable, :start]
  subscribes :restart, resources('cookbook_file[/etc/sudoers.d/cloud-init]', 'package[cloud-init]')
end
service('crond') do
  action [:enable, :start]
  subscribes :restart, resources('package[cronie]')
end
service('docker') do
  action [:enable, :start]
  subscribes :restart, resources('package[docker]')
end
service('ip6tables') do
  action [:enable, :start]
  subscribes :restart, resources('package[iptables]')
end
service('iptables') do
  action [:enable, :start]
  subscribes :restart, resources('package[iptables]')
end
service('irqbalance') do
  action [:enable, :start]
  subscribes :restart, resources('package[irqbalance]')
end
service('mdmonitor') do
  action [:enable, :start]
  subscribes :restart, resources('package[mdadm]')
end
service('messagebus') do
  action [:enable, :start]
  subscribes :restart, resources('package[dbus]')
end
service('netfs') do
  action [:enable, :start]
  subscribes :restart, resources('package[initscripts]')
end
service('network') do
  action [:enable, :start]
  subscribes :restart, resources('package[initscripts]')
end
service('nfslock') do
  action [:enable, :start]
  subscribes :restart, resources('package[nfs-utils]')
end
service('rpcbind') do
  action [:enable, :start]
  subscribes :restart, resources('package[rpcbind]')
end
service('rpcgssd') do
  action [:enable, :start]
  subscribes :restart, resources('package[nfs-utils]')
end
service('rpcidmapd') do
  action [:enable, :start]
  subscribes :restart, resources('package[nfs-utils]')
end
service('rsyslog') do
  action [:enable, :start]
  subscribes :restart, resources('package[rsyslog]')
end
service('sendmail') do
  action [:enable, :start]
  subscribes :restart, resources('cookbook_file[/etc/mail/mailertable.db]', 'cookbook_file[/etc/mail/access.db]', 'cookbook_file[/etc/mail/virtusertable.db]', 'cookbook_file[/etc/mail/domaintable.db]', 'package[sendmail]')
end
service('sshd') do
  action [:enable, :start]
  subscribes :restart, resources('cookbook_file[/etc/ssh/sshd_config]', 'package[openssh-server]', 'execute[eded041e549437d1590721f0d8dfead7859e091d.tar]')
end
service('serial') do
  action [:enable, :start]
  provider Chef::Provider::Service::Upstart
  subscribes :restart, resources('cookbook_file[/etc/securetty]', 'package[initscripts]')
end
